services:
  frontend:
    image: ${IMAGE_REGISTRY:-pythinker}/pythinker-frontend:${IMAGE_TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pythinker-network
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    image: ${IMAGE_REGISTRY:-pythinker}/pythinker-backend:${IMAGE_TAG:-latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    depends_on:
      - sandbox
      - mongodb
      - redis
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./mcp.json:/etc/mcp.json # Mount MCP servers directory
    networks:
      - pythinker-network
    env_file:
      - .env

  sandbox:
    image: ${IMAGE_REGISTRY:-pythinker}/pythinker-sandbox:${IMAGE_TAG:-latest}
    build:
      context: ./sandbox
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    hostname: sandbox
    restart: unless-stopped
    ports:
      - "8080:8080"  # Sandbox API
      - "5902:5900"  # VNC
      - "6080:6080"  # NoVNC websocket
    networks:
      - pythinker-network

  mongodb:
    image: mongo:7.0
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    #ports:
    #  - "27017:27017"
    networks:
      - pythinker-network

  redis:
    image: redis:7.0
    restart: unless-stopped
    networks:
      - pythinker-network

  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped
    networks:
      - pythinker-network

volumes:
  mongodb_data:
    name: pythinker-mongodb-data

networks:
  pythinker-network:
    name: pythinker-network
    driver: bridge
