"""Repository protocol for canvas project persistence."""

from typing import Protocol

from app.domain.models.canvas import CanvasProject, CanvasVersion


class CanvasRepository(Protocol):
    """Protocol for canvas project persistence."""

    async def save(self, project: CanvasProject) -> CanvasProject: ...

    async def find_by_id(self, project_id: str) -> CanvasProject | None: ...

    async def find_by_session_id(self, session_id: str) -> CanvasProject | None: ...

    async def find_by_user_id(self, user_id: str, skip: int = 0, limit: int = 50) -> list[CanvasProject]: ...

    async def update(self, project_id: str, project: CanvasProject) -> CanvasProject | None: ...

    async def delete(self, project_id: str) -> bool: ...

    async def count_by_user_id(self, user_id: str) -> int: ...

    async def save_version(self, version: CanvasVersion) -> CanvasVersion: ...

    async def get_versions(self, project_id: str, limit: int = 20) -> list[CanvasVersion]: ...

    async def get_version(self, project_id: str, version: int) -> CanvasVersion | None: ...

    async def count_versions(self, project_id: str) -> int: ...
