"""Repository protocols for connector persistence."""

from typing import Protocol

from app.domain.models.connector import Connector, ConnectorType, UserConnector


class ConnectorRepository(Protocol):
    """Protocol for connector catalog persistence."""

    async def get_all(self) -> list[Connector]: ...

    async def get_by_id(self, connector_id: str) -> Connector | None: ...

    async def get_by_type(self, connector_type: ConnectorType) -> list[Connector]: ...

    async def create(self, connector: Connector) -> Connector: ...

    async def upsert(self, connector: Connector) -> Connector: ...

    async def delete(self, connector_id: str) -> bool: ...

    async def search(
        self, query: str | None = None, connector_type: ConnectorType | None = None
    ) -> list[Connector]: ...


class UserConnectorRepository(Protocol):
    """Protocol for user connector instance persistence."""

    async def get_by_user(self, user_id: str) -> list[UserConnector]: ...

    async def get_by_id(self, user_connector_id: str) -> UserConnector | None: ...

    async def get_by_user_and_connector(self, user_id: str, connector_id: str) -> UserConnector | None: ...

    async def get_connected_by_user(self, user_id: str) -> list[UserConnector]: ...

    async def get_mcp_connectors_by_user(self, user_id: str) -> list[UserConnector]: ...

    async def create(self, user_connector: UserConnector) -> UserConnector: ...

    async def update(self, user_connector_id: str, user_connector: UserConnector) -> UserConnector | None: ...

    async def delete(self, user_connector_id: str) -> bool: ...

    async def delete_by_user_and_connector(self, user_id: str, connector_id: str) -> bool: ...
