"""Repository protocol for screenshot persistence."""

from typing import Protocol

from app.domain.models.screenshot import SessionScreenshot


class ScreenshotRepository(Protocol):
    async def save(self, screenshot: SessionScreenshot) -> None: ...
    async def find_by_session(self, session_id: str, limit: int = 500, offset: int = 0) -> list[SessionScreenshot]: ...
    async def find_by_id(self, screenshot_id: str) -> SessionScreenshot | None: ...
    async def count_by_session(self, session_id: str) -> int: ...
    async def delete_by_session(self, session_id: str) -> int: ...
