export const MAX_CREATE_SESSION_WAIT_SECONDS = 5
export const CHAT_EVENT_TIMEOUT_SECONDS = 300
export const CHAT_EVENT_HARD_TIMEOUT_SECONDS = 1800
export const CHAT_WAIT_BEACON_INTERVAL_SECONDS = 20

export const SSE_PROTOCOL_VERSION = '2'
export const SSE_RETRY_MAX_ATTEMPTS = 7
export const SSE_RETRY_BASE_DELAY_MS = 1000
export const SSE_RETRY_MAX_DELAY_MS = 45_000
export const SSE_RETRY_JITTER_RATIO = 0.25
export const SSE_HEARTBEAT_INTERVAL_SECONDS = 30

export const SSE_STALE_CHECK_INTERVAL_MS = 5_000
export const SSE_HEARTBEAT_LIVENESS_MS = Math.trunc(SSE_HEARTBEAT_INTERVAL_SECONDS * 1.5 * 1000)
export const SSE_STALE_TIMEOUT_MS = Math.trunc(SSE_HEARTBEAT_INTERVAL_SECONDS * 4 * 1000)

/** No substantive SSE events while heartbeats continue — typical during long LLM turns. */
export const HANDLER_QUIET_THRESHOLD_MS = 35_000

export const WORKFLOW_TIMING_CONTRACT = Object.freeze({
  MAX_CREATE_SESSION_WAIT_SECONDS,
  CHAT_EVENT_TIMEOUT_SECONDS,
  CHAT_EVENT_HARD_TIMEOUT_SECONDS,
  CHAT_WAIT_BEACON_INTERVAL_SECONDS,
  SSE_PROTOCOL_VERSION,
  SSE_RETRY_MAX_ATTEMPTS,
  SSE_RETRY_BASE_DELAY_MS,
  SSE_RETRY_MAX_DELAY_MS,
  SSE_RETRY_JITTER_RATIO,
  SSE_HEARTBEAT_INTERVAL_SECONDS,
  SSE_STALE_CHECK_INTERVAL_MS,
  SSE_HEARTBEAT_LIVENESS_MS,
  SSE_STALE_TIMEOUT_MS,
  HANDLER_QUIET_THRESHOLD_MS,
})
