"""Authoritative workflow timing values shared across backend surfaces."""

MAX_CREATE_SESSION_WAIT_SECONDS = 5.0
CHAT_EVENT_TIMEOUT_SECONDS = 300.0
CHAT_EVENT_HARD_TIMEOUT_SECONDS = 1800.0
CHAT_WAIT_BEACON_INTERVAL_SECONDS = 20.0

SSE_PROTOCOL_VERSION = "2"
SSE_RETRY_MAX_ATTEMPTS = 7
SSE_RETRY_BASE_DELAY_MS = 1000
SSE_RETRY_MAX_DELAY_MS = 45000
SSE_RETRY_JITTER_RATIO = 0.25
SSE_HEARTBEAT_INTERVAL_SECONDS = 30.0

SSE_STALE_CHECK_INTERVAL_MS = 5000
SSE_HEARTBEAT_LIVENESS_MS = int(SSE_HEARTBEAT_INTERVAL_SECONDS * 1.5 * 1000)
SSE_STALE_TIMEOUT_MS = int(SSE_HEARTBEAT_INTERVAL_SECONDS * 4 * 1000)
